//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoEngine.Logins {
    
    
    public partial class LoginIndex {
        
        /// <summary>
        /// BoardSearchFormSingleControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MemoEngine.Logins.Controls.BoardSearchFormSingleControl BoardSearchFormSingleControl;
        
        /// <summary>
        /// lblTotalRecord control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblTotalRecord;
        
        /// <summary>
        /// ctlBoardList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView ctlBoardList;
        
        /// <summary>
        /// AdvancedPagingSingleWithBootstrap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MemoEngine.Logins.Controls.AdvancedPagingSingleWithBootstrap AdvancedPagingSingleWithBootstrap;
    }
}
